# Form implementation generated from reading ui file 'ChartVisualization.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(499, 561)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(parent=self.centralwidget)
        self.groupBox.setObjectName("groupBox")
        self.pushButtonAgeDis = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButtonAgeDis.setGeometry(QtCore.QRect(10, 30, 161, 31))
        self.pushButtonAgeDis.setObjectName("pushButtonAgeDis")
        self.label = QtWidgets.QLabel(parent=self.groupBox)
        self.label.setGeometry(QtCore.QRect(180, 40, 55, 16))
        self.label.setObjectName("label")
        self.lineEditFromAge = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditFromAge.setGeometry(QtCore.QRect(240, 31, 51, 31))
        self.lineEditFromAge.setObjectName("lineEditFromAge")
        self.label_2 = QtWidgets.QLabel(parent=self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(300, 40, 55, 16))
        self.label_2.setObjectName("label_2")
        self.lineEditToAge = QtWidgets.QLineEdit(parent=self.groupBox)
        self.lineEditToAge.setGeometry(QtCore.QRect(360, 31, 51, 31))
        self.lineEditToAge.setObjectName("lineEditToAge")
        self.pushButtonSpendScore = QtWidgets.QPushButton(parent=self.groupBox)
        self.pushButtonSpendScore.setGeometry(QtCore.QRect(420, 30, 161, 31))
        self.pushButtonSpendScore.setObjectName("pushButtonSpendScore")
        self.verticalLayout.addWidget(self.groupBox)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        self.verticalLayoutPlot = QtWidgets.QVBoxLayout()
        self.verticalLayoutPlot.setObjectName("verticalLayoutPlot")
        self.verticalLayout_2.addLayout(self.verticalLayoutPlot)
        self.pushButtonBack = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonBack.setObjectName("pushButtonBack")
        self.verticalLayout_2.addWidget(self.pushButtonBack)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 499, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.groupBox.setTitle(_translate("MainWindow", "Chosse Statistic"))
        self.pushButtonAgeDis.setText(_translate("MainWindow", "Customer Age Distribution"))
        self.label.setText(_translate("MainWindow", "From Age"))
        self.lineEditFromAge.setText(_translate("MainWindow", "19"))
        self.label_2.setText(_translate("MainWindow", "From Age"))
        self.lineEditToAge.setText(_translate("MainWindow", "25"))
        self.pushButtonSpendScore.setText(_translate("MainWindow", "Customer_spend_score"))
        self.pushButtonBack.setText(_translate("MainWindow", "Back"))
