# Form implementation generated from reading ui file 'SaleMainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(665, 536)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.pushButtonCustomer = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonCustomer.setObjectName("pushButtonCustomer")
        self.verticalLayout.addWidget(self.pushButtonCustomer)
        self.pushButtonCustomerSpendScore = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonCustomerSpendScore.setObjectName("pushButtonCustomerSpendScore")
        self.verticalLayout.addWidget(self.pushButtonCustomerSpendScore)
        self.pushButtonStatistic = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButtonStatistic.setObjectName("pushButtonStatistic")
        self.verticalLayout.addWidget(self.pushButtonStatistic)
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout.addWidget(self.tableWidget)
        self.verticalLayout_2.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 665, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.pushButtonCustomer.setText(_translate("MainWindow", "Load Customer"))
        self.pushButtonCustomerSpendScore.setText(_translate("MainWindow", "customer_spend_score"))
        self.pushButtonStatistic.setText(_translate("MainWindow", "Chart Visualization"))
